export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACE_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_WORKSPACE_COLLECTION_ID!;
export const IMAGE_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGE_BUCKET_ID!;
export const MEMBERS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_COLLECTION_ID!;
export const PROJECTS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_COLLECTION_ID!;
